services:
  monolith:
    build:
      context: ./apps/monolith
      dockerfile: Dockerfile
    volumes:
      - ./keys/private.pem:/app/keys/private.pem:ro
      - ./keys/public.pem:/app/keys/public.pem:ro
    ports:
      - "8000:8000"